import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from "@/pages/component/navbar";
import Feed from "@/pages/component/Feed";
import {useAuth} from "@/pages/api/AuthContext";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>5 Chan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/neco-icon.ico"/>
      </Head>
      <main>
          <Navigation/>
          <Feed/>
      </main>
    </>
  )
}
